openapi: 3.0.0
info:
  version: 1.0.0
  title: Ravimoshark Contract API
  termsOfService: 'https://ravimoshark.com/terms/'
  contact:
    email: dev@ravimoshark.com
    url: 'http://ravimoshark.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  description: >
    This is an API to interact with Ravimoshark contracts database.

    # Introduction

    This API allow to create, modify and delete contracts and machines. It also
    interacts with machines imported from SAGE database.

    # User Authentication

    This API does not contain any kind of user validation but It request to have
    a valid authentication user to interact with it.
    For more information about user Authentication, please refer to
    [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest).
externalDocs:
  description: Find out how to interact with Ravimoshark's APIs.
  url: 'https://ravimoshark.com/back/apis/auth/latest'
tags:
  - name: Contracts
    description: Operations about contracts.
  - name: Machines
    description: Operations about machines.
  - name: ImportedMachines
    description: Operations about imported machines.
servers:
  - url: 'http://localhost:8000'
  - url: 'https://ravimoshark.com/back/apis/contract/v1'
  - url: 'https://ravimoshark.com/back/apis/contract/latest'
